name: first startup
on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'lib/galaxy_test/selenium/**'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'lib/galaxy_test/selenium/**'
env:
  YARN_INSTALL_OPTS: --frozen-lockfile
concurrency:
  group: first-startup-${{ github.ref }}
  cancel-in-progress: true
jobs:

  test:
    name: Startup test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.9']
        webserver: ['uwsgi']
        include:
          - python-version: '3.9'
            webserver: 'dev'
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'galaxy root'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip dir
      uses: actions/cache@v1
      id: pip-cache
      with:
        path: ~/.cache/pip
        key: pip-cache-${{ matrix.python-version }}-${{ hashFiles('galaxy root/requirements.txt') }}
    - uses: mvdbeek/gha-yarn-cache@master
      with:
        yarn-lock-file: 'galaxy root/client/yarn.lock'
    - name: Install tox
      run: pip install tox
      # Use this job to test the latest migrations
    - run: wget -q https://github.com/jmchilton/galaxy-downloads/raw/master/db_gx_rev_0141.sqlite
    - run: mv db_gx_rev_0141.sqlite 'galaxy root'/database/universe.sqlite
    - name: run tests
      run: tox -e first_startup
      working-directory: 'galaxy root'
      env:
        APP_WEBSERVER: ${{ matrix.webserver }}
